// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgent(arg1, arg2) {
  return window['go']['main']['App']['AddAgent'](arg1, arg2);
}

export function AlertDialog(arg1, arg2) {
  return window['go']['main']['App']['AlertDialog'](arg1, arg2);
}

export function AnswerQuestion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2, arg3, arg4, arg5);
}

export function ClearAPIKey() {
  return window['go']['main']['App']['ClearAPIKey']();
}

export function ClearActiveSession() {
  return window['go']['main']['App']['ClearActiveSession']();
}

export function CompleteHyperLogin(arg1, arg2) {
  return window['go']['main']['App']['CompleteHyperLogin'](arg1, arg2);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentTotalUnread(arg1) {
  return window['go']['main']['App']['GetAgentTotalUnread'](arg1);
}

export function GetAllSessionNames(arg1) {
  return window['go']['main']['App']['GetAllSessionNames'](arg1);
}

export function GetAllWorkspaces() {
  return window['go']['main']['App']['GetAllWorkspaces']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetConversation(arg1, arg2) {
  return window['go']['main']['App']['GetConversation'](arg1, arg2);
}

export function GetCurrentWorkspaceID() {
  return window['go']['main']['App']['GetCurrentWorkspaceID']();
}

export function GetPlanFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetPlanFilePath'](arg1, arg2);
}

export function GetSessionName(arg1, arg2) {
  return window['go']['main']['App']['GetSessionName'](arg1, arg2);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubagentConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSubagentConversation'](arg1, arg2, arg3);
}

export function GetUnreadCounts(arg1) {
  return window['go']['main']['App']['GetUnreadCounts'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsClaudeInstalled() {
  return window['go']['main']['App']['IsClaudeInstalled']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkSessionViewed(arg1, arg2) {
  return window['go']['main']['App']['MarkSessionViewed'](arg1, arg2);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function ReadPlanFile(arg1) {
  return window['go']['main']['App']['ReadPlanFile'](arg1);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SaveWorkspaceWithRename(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspaceWithRename'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function SendMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetActiveSession(arg1, arg2) {
  return window['go']['main']['App']['SetActiveSession'](arg1, arg2);
}

export function SetSessionName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionName'](arg1, arg2, arg3);
}

export function StartHyperLogin() {
  return window['go']['main']['App']['StartHyperLogin']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}
