// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptPlanReview(arg1) {
  return window['go']['main']['App']['AcceptPlanReview'](arg1);
}

export function AddAgent(arg1, arg2) {
  return window['go']['main']['App']['AddAgent'](arg1, arg2);
}

export function AlertDialog(arg1, arg2) {
  return window['go']['main']['App']['AlertDialog'](arg1, arg2);
}

export function AnswerMCPQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerMCPQuestion'](arg1, arg2);
}

export function AnswerPermissionRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnswerPermissionRequest'](arg1, arg2, arg3, arg4);
}

export function AnswerQuestion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2, arg3, arg4, arg5);
}

export function AppendCancellationMarker(arg1, arg2) {
  return window['go']['main']['App']['AppendCancellationMarker'](arg1, arg2);
}

export function CancelSession(arg1, arg2) {
  return window['go']['main']['App']['CancelSession'](arg1, arg2);
}

export function CheckAgentScaffold(arg1) {
  return window['go']['main']['App']['CheckAgentScaffold'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ClearAPIKey() {
  return window['go']['main']['App']['ClearAPIKey']();
}

export function ClearActiveSession() {
  return window['go']['main']['App']['ClearActiveSession']();
}

export function ClearAgentInbox(arg1) {
  return window['go']['main']['App']['ClearAgentInbox'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CompleteHyperLogin(arg1, arg2) {
  return window['go']['main']['App']['CompleteHyperLogin'](arg1, arg2);
}

export function ConfirmDialog(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDialog'](arg1, arg2);
}

export function CreateTerminal(arg1) {
  return window['go']['main']['App']['CreateTerminal'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteInboxMessage(arg1, arg2) {
  return window['go']['main']['App']['DeleteInboxMessage'](arg1, arg2);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentPermissions(arg1) {
  return window['go']['main']['App']['GetAgentPermissions'](arg1);
}

export function GetAgentPermissionsOrGlobal(arg1) {
  return window['go']['main']['App']['GetAgentPermissionsOrGlobal'](arg1);
}

export function GetAgentTotalUnread(arg1) {
  return window['go']['main']['App']['GetAgentTotalUnread'](arg1);
}

export function GetAllSessionNames(arg1) {
  return window['go']['main']['App']['GetAllSessionNames'](arg1);
}

export function GetAllWorkspaces() {
  return window['go']['main']['App']['GetAllWorkspaces']();
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetClaudeMD(arg1) {
  return window['go']['main']['App']['GetClaudeMD'](arg1);
}

export function GetClaudePermissions(arg1) {
  return window['go']['main']['App']['GetClaudePermissions'](arg1);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetConversation(arg1, arg2) {
  return window['go']['main']['App']['GetConversation'](arg1, arg2);
}

export function GetConversationPaged(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetConversationPaged'](arg1, arg2, arg3, arg4);
}

export function GetCurrentWorkspace() {
  return window['go']['main']['App']['GetCurrentWorkspace']();
}

export function GetCurrentWorkspaceID() {
  return window['go']['main']['App']['GetCurrentWorkspaceID']();
}

export function GetDefaultMCPToolAvailability() {
  return window['go']['main']['App']['GetDefaultMCPToolAvailability']();
}

export function GetDefaultMCPToolInstructions() {
  return window['go']['main']['App']['GetDefaultMCPToolInstructions']();
}

export function GetDefaultPermissionSets() {
  return window['go']['main']['App']['GetDefaultPermissionSets']();
}

export function GetDefaultTemplateMD() {
  return window['go']['main']['App']['GetDefaultTemplateMD']();
}

export function GetGlobalClaudeMD() {
  return window['go']['main']['App']['GetGlobalClaudeMD']();
}

export function GetGlobalDirectories() {
  return window['go']['main']['App']['GetGlobalDirectories']();
}

export function GetGlobalPermissions() {
  return window['go']['main']['App']['GetGlobalPermissions']();
}

export function GetInboxMessages(arg1) {
  return window['go']['main']['App']['GetInboxMessages'](arg1);
}

export function GetInboxTotalCount(arg1) {
  return window['go']['main']['App']['GetInboxTotalCount'](arg1);
}

export function GetInboxUnreadCount(arg1) {
  return window['go']['main']['App']['GetInboxUnreadCount'](arg1);
}

export function GetMCPServerPort() {
  return window['go']['main']['App']['GetMCPServerPort']();
}

export function GetMCPToolAvailability() {
  return window['go']['main']['App']['GetMCPToolAvailability']();
}

export function GetMCPToolInstructions() {
  return window['go']['main']['App']['GetMCPToolInstructions']();
}

export function GetMenu() {
  return window['go']['main']['App']['GetMenu']();
}

export function GetOrderedPermissionSets() {
  return window['go']['main']['App']['GetOrderedPermissionSets']();
}

export function GetPendingMCPQuestions() {
  return window['go']['main']['App']['GetPendingMCPQuestions']();
}

export function GetPendingPermissionRequests() {
  return window['go']['main']['App']['GetPendingPermissionRequests']();
}

export function GetPermissionSets() {
  return window['go']['main']['App']['GetPermissionSets']();
}

export function GetPlanFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetPlanFilePath'](arg1, arg2);
}

export function GetSessionName(arg1, arg2) {
  return window['go']['main']['App']['GetSessionName'](arg1, arg2);
}

export function GetSessions(arg1) {
  return window['go']['main']['App']['GetSessions'](arg1);
}

export function GetSetByCommand(arg1) {
  return window['go']['main']['App']['GetSetByCommand'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubagentConversation(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSubagentConversation'](arg1, arg2, arg3);
}

export function GetTerminals() {
  return window['go']['main']['App']['GetTerminals']();
}

export function GetUnreadCounts(arg1) {
  return window['go']['main']['App']['GetUnreadCounts'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function HasAgentPermissions(arg1) {
  return window['go']['main']['App']['HasAgentPermissions'](arg1);
}

export function HasExistingClaudeSettings(arg1) {
  return window['go']['main']['App']['HasExistingClaudeSettings'](arg1);
}

export function ImportFromClaudeSettings(arg1) {
  return window['go']['main']['App']['ImportFromClaudeSettings'](arg1);
}

export function InjectInboxMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['InjectInboxMessage'](arg1, arg2, arg3);
}

export function IsClaudeInstalled() {
  return window['go']['main']['App']['IsClaudeInstalled']();
}

export function ListFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2, arg3);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MarkAllInboxRead(arg1) {
  return window['go']['main']['App']['MarkAllInboxRead'](arg1);
}

export function MarkInboxMessageRead(arg1, arg2) {
  return window['go']['main']['App']['MarkInboxMessageRead'](arg1, arg2);
}

export function MarkSessionViewed(arg1, arg2) {
  return window['go']['main']['App']['MarkSessionViewed'](arg1, arg2);
}

export function MergeToolsFromGlobal(arg1) {
  return window['go']['main']['App']['MergeToolsFromGlobal'](arg1);
}

export function NewSession(arg1) {
  return window['go']['main']['App']['NewSession'](arg1);
}

export function PreviewMergeTools(arg1) {
  return window['go']['main']['App']['PreviewMergeTools'](arg1);
}

export function PreviewRevertTools(arg1) {
  return window['go']['main']['App']['PreviewRevertTools'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function ReadImageAsDataURL(arg1) {
  return window['go']['main']['App']['ReadImageAsDataURL'](arg1);
}

export function ReadPlanFile(arg1) {
  return window['go']['main']['App']['ReadPlanFile'](arg1);
}

export function RefreshMenu() {
  return window['go']['main']['App']['RefreshMenu']();
}

export function RefreshSessions(arg1) {
  return window['go']['main']['App']['RefreshSessions'](arg1);
}

export function RejectPlanReview(arg1, arg2) {
  return window['go']['main']['App']['RejectPlanReview'](arg1, arg2);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function RenameWorkspace(arg1, arg2) {
  return window['go']['main']['App']['RenameWorkspace'](arg1, arg2);
}

export function ResetMCPToolInstructions() {
  return window['go']['main']['App']['ResetMCPToolInstructions']();
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RevertAgentToGlobal(arg1) {
  return window['go']['main']['App']['RevertAgentToGlobal'](arg1);
}

export function SaveAgentPermissions(arg1, arg2) {
  return window['go']['main']['App']['SaveAgentPermissions'](arg1, arg2);
}

export function SaveClaudeMD(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeMD'](arg1, arg2);
}

export function SaveClaudePermissions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveClaudePermissions'](arg1, arg2, arg3, arg4);
}

export function SaveDefaultPermissionSets(arg1) {
  return window['go']['main']['App']['SaveDefaultPermissionSets'](arg1);
}

export function SaveDefaultTemplateMD(arg1) {
  return window['go']['main']['App']['SaveDefaultTemplateMD'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveGlobalClaudeMD(arg1) {
  return window['go']['main']['App']['SaveGlobalClaudeMD'](arg1);
}

export function SaveGlobalPermissions(arg1) {
  return window['go']['main']['App']['SaveGlobalPermissions'](arg1);
}

export function SaveMCPToolAvailability(arg1) {
  return window['go']['main']['App']['SaveMCPToolAvailability'](arg1);
}

export function SaveMCPToolInstructions(arg1) {
  return window['go']['main']['App']['SaveMCPToolInstructions'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['main']['App']['SaveWorkspace'](arg1);
}

export function SaveWorkspaceWithRename(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkspaceWithRename'](arg1, arg2);
}

export function ScaffoldAgent(arg1, arg2) {
  return window['go']['main']['App']['ScaffoldAgent'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectWorkspaceFolder() {
  return window['go']['main']['App']['SelectWorkspaceFolder']();
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetActiveSession(arg1, arg2) {
  return window['go']['main']['App']['SetActiveSession'](arg1, arg2);
}

export function SetSessionName(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSessionName'](arg1, arg2, arg3);
}

export function SkipMCPQuestion(arg1) {
  return window['go']['main']['App']['SkipMCPQuestion'](arg1);
}

export function SkipPlanReview(arg1) {
  return window['go']['main']['App']['SkipPlanReview'](arg1);
}

export function StartHyperLogin() {
  return window['go']['main']['App']['StartHyperLogin']();
}

export function SwitchWorkspace(arg1) {
  return window['go']['main']['App']['SwitchWorkspace'](arg1);
}

export function SyncToClaudeSettings(arg1) {
  return window['go']['main']['App']['SyncToClaudeSettings'](arg1);
}

export function TouchPlanFile(arg1, arg2) {
  return window['go']['main']['App']['TouchPlanFile'](arg1, arg2);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
