// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {workspace} from '../models';
import {main} from '../models';
import {terminal} from '../models';
import {permissions} from '../models';
import {auth} from '../models';
import {types} from '../models';
import {mcpserver} from '../models';
import {menu} from '../models';
import {settings} from '../models';

export function AddAgent(arg1:string,arg2:string):Promise<workspace.Agent>;

export function AlertDialog(arg1:string,arg2:string):Promise<void>;

export function AnswerMCPQuestion(arg1:string,arg2:Record<string, string>):Promise<void>;

export function AnswerPermissionRequest(arg1:string,arg2:boolean,arg3:boolean,arg4:string):Promise<void>;

export function AnswerQuestion(arg1:string,arg2:string,arg3:string,arg4:Array<Record<string, any>>,arg5:Record<string, string>):Promise<void>;

export function AppendCancellationMarker(arg1:string,arg2:string):Promise<void>;

export function CancelSession(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function ClearAPIKey():Promise<void>;

export function ClearActiveSession():Promise<void>;

export function ClearAgentInbox(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CompleteHyperLogin(arg1:string,arg2:number):Promise<void>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function CreateTerminal(arg1:string):Promise<terminal.TerminalInfo>;

export function CreateWorkspace(arg1:string):Promise<workspace.Workspace>;

export function DeleteInboxMessage(arg1:string,arg2:string):Promise<boolean>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function GetAgent(arg1:string):Promise<workspace.Agent>;

export function GetAgentPermissions(arg1:string):Promise<permissions.ClaudeFuPermissions>;

export function GetAgentPermissionsOrGlobal(arg1:string):Promise<permissions.ClaudeFuPermissions>;

export function GetAgentTotalUnread(arg1:string):Promise<number>;

export function GetAllSessionNames(arg1:string):Promise<Record<string, string>>;

export function GetAllWorkspaces():Promise<Array<workspace.WorkspaceSummary>>;

export function GetAuthStatus():Promise<auth.AuthStatus>;

export function GetClaudeMD(arg1:string):Promise<string>;

export function GetClaudePermissions(arg1:string):Promise<main.ClaudePermissions>;

export function GetConfigPath():Promise<string>;

export function GetConversation(arg1:string,arg2:string):Promise<Array<types.Message>>;

export function GetConversationPaged(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.ConversationResult>;

export function GetCurrentWorkspace():Promise<workspace.Workspace>;

export function GetCurrentWorkspaceID():Promise<string>;

export function GetDefaultMCPToolAvailability():Promise<mcpserver.ToolAvailability>;

export function GetDefaultMCPToolInstructions():Promise<mcpserver.ToolInstructions>;

export function GetDefaultPermissionSets():Promise<Record<string, string>>;

export function GetGlobalDirectories():Promise<Array<string>>;

export function GetGlobalPermissions():Promise<permissions.ClaudeFuPermissions>;

export function GetInboxMessages(arg1:string):Promise<Array<mcpserver.InboxMessage>>;

export function GetInboxTotalCount(arg1:string):Promise<number>;

export function GetInboxUnreadCount(arg1:string):Promise<number>;

export function GetMCPServerPort():Promise<number>;

export function GetMCPToolAvailability():Promise<mcpserver.ToolAvailability>;

export function GetMCPToolInstructions():Promise<mcpserver.ToolInstructions>;

export function GetMenu():Promise<menu.Menu>;

export function GetOrderedPermissionSets():Promise<Array<permissions.PermissionSet>>;

export function GetPendingMCPQuestions():Promise<Array<main.MCPPendingQuestion>>;

export function GetPendingPermissionRequests():Promise<Array<main.MCPPendingPermission>>;

export function GetPermissionSets():Promise<Record<string, permissions.PermissionSet>>;

export function GetPlanFilePath(arg1:string,arg2:string):Promise<string>;

export function GetSessionName(arg1:string,arg2:string):Promise<string>;

export function GetSessions(arg1:string):Promise<Array<types.Session>>;

export function GetSetByCommand(arg1:string):Promise<main.PermissionSetMatch>;

export function GetSettings():Promise<settings.Settings>;

export function GetSubagentConversation(arg1:string,arg2:string,arg3:string):Promise<Array<types.Message>>;

export function GetTerminals():Promise<Array<terminal.TerminalInfo>>;

export function GetUnreadCounts(arg1:string):Promise<Record<string, number>>;

export function GetVersion():Promise<string>;

export function HasAgentPermissions(arg1:string):Promise<boolean>;

export function HasExistingClaudeSettings(arg1:string):Promise<boolean>;

export function ImportFromClaudeSettings(arg1:string):Promise<main.ImportResult>;

export function InjectInboxMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IsClaudeInstalled():Promise<boolean>;

export function ListFiles(arg1:string,arg2:string,arg3:number):Promise<Array<main.FileInfo>>;

export function Logout():Promise<void>;

export function MarkAllInboxRead(arg1:string):Promise<void>;

export function MarkInboxMessageRead(arg1:string,arg2:string):Promise<boolean>;

export function MarkSessionViewed(arg1:string,arg2:string):Promise<void>;

export function MergeToolsFromGlobal(arg1:string):Promise<void>;

export function NewSession(arg1:string):Promise<string>;

export function PreviewMergeTools(arg1:string):Promise<permissions.PermissionsDiff>;

export function PreviewRevertTools(arg1:string):Promise<permissions.PermissionsDiff>;

export function ReadFileContent(arg1:string):Promise<string>;

export function ReadImageAsDataURL(arg1:string):Promise<string>;

export function ReadPlanFile(arg1:string):Promise<string>;

export function RefreshMenu():Promise<void>;

export function RefreshSessions(arg1:string):Promise<Array<types.Session>>;

export function RemoveAgent(arg1:string):Promise<void>;

export function RenameWorkspace(arg1:string,arg2:string):Promise<void>;

export function ResetMCPToolInstructions():Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RevertAgentToGlobal(arg1:string):Promise<void>;

export function SaveAgentPermissions(arg1:string,arg2:permissions.ClaudeFuPermissions):Promise<void>;

export function SaveClaudeMD(arg1:string,arg2:string):Promise<void>;

export function SaveClaudePermissions(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>):Promise<void>;

export function SaveDefaultPermissionSets(arg1:Record<string, string>):Promise<void>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveGlobalPermissions(arg1:permissions.ClaudeFuPermissions):Promise<void>;

export function SaveMCPToolAvailability(arg1:mcpserver.ToolAvailability):Promise<void>;

export function SaveMCPToolInstructions(arg1:mcpserver.ToolInstructions):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SaveWorkspace(arg1:workspace.Workspace):Promise<void>;

export function SaveWorkspaceWithRename(arg1:workspace.Workspace,arg2:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectWorkspaceFolder():Promise<string>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:Array<types.Attachment>,arg5:boolean):Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetActiveSession(arg1:string,arg2:string):Promise<void>;

export function SetSessionName(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SkipMCPQuestion(arg1:string):Promise<void>;

export function StartHyperLogin():Promise<auth.DeviceAuthInfo>;

export function SwitchWorkspace(arg1:string):Promise<workspace.Workspace>;

export function SyncToClaudeSettings(arg1:string):Promise<void>;

export function UpdateAgent(arg1:workspace.Agent):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
